__name__ = "orix"
__version__ = "0.2.0rc1"
__author__ = "Ben Martineau & Phillip Crout"
__author_email__ = "pyxem.team@gmail.com"
__description__ = "Orientation, rotation, quaternion, and crystal symmetry handling in Python."
